name: hyper_garage_sale
description: A Hyper Garage Sale application

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.4
  firebase_core: ^2.30.0
  firebase_core_platform_interface: ^5.0.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  google_sign_in: ^5.4.2
  path_provider: ^2.0.6
  provider: "^6.0.1"
  image_picker: "^0.8.4"
  intl: ^0.18.1
  page_view_indicators: "^2.0.0"
  google_fonts: ^6.2.1
  firebase_ui_auth: ^1.13.1
  firebase_app_check: ^0.2.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flutterfire_300x.png
    - assets/placeholder-image.jpg
