// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbRR9h7qBaJFIukckqrgL5CJA3yq5-Vrc',
    appId: '1:670016645149:web:8e81e49ebedda51f89fef4',
    messagingSenderId: '670016645149',
    projectId: 'info6350-final',
    authDomain: 'info6350-final.firebaseapp.com',
    databaseURL: 'https://info6350-final-default-rtdb.firebaseio.com',
    storageBucket: 'info6350-final.appspot.com',
    measurementId: 'G-1VZ8HWKHFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSYO7-95rDQdC_xcb_fsxN5Dn2Y3FSNiQ',
    appId: '1:670016645149:android:66f53576cb0e064589fef4',
    messagingSenderId: '670016645149',
    projectId: 'info6350-final',
    databaseURL: 'https://info6350-final-default-rtdb.firebaseio.com',
    storageBucket: 'info6350-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5FoMBVvhnppJoxFCFmCoeKdHwPJT6H60',
    appId: '1:670016645149:ios:7091904afdbe555f89fef4',
    messagingSenderId: '670016645149',
    projectId: 'info6350-final',
    databaseURL: 'https://info6350-final-default-rtdb.firebaseio.com',
    storageBucket: 'info6350-final.appspot.com',
    iosBundleId: 'com.example.hyperGarageSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5FoMBVvhnppJoxFCFmCoeKdHwPJT6H60',
    appId: '1:670016645149:ios:7091904afdbe555f89fef4',
    messagingSenderId: '670016645149',
    projectId: 'info6350-final',
    databaseURL: 'https://info6350-final-default-rtdb.firebaseio.com',
    storageBucket: 'info6350-final.appspot.com',
    iosBundleId: 'com.example.hyperGarageSale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbRR9h7qBaJFIukckqrgL5CJA3yq5-Vrc',
    appId: '1:670016645149:web:12b981620aeb653389fef4',
    messagingSenderId: '670016645149',
    projectId: 'info6350-final',
    authDomain: 'info6350-final.firebaseapp.com',
    databaseURL: 'https://info6350-final-default-rtdb.firebaseio.com',
    storageBucket: 'info6350-final.appspot.com',
    measurementId: 'G-KSES2GVFDK',
  );

}